include:
  - 'base.gitlab-ci.yml'

.base-rs:
  image: rust:latest
  rules:
    - changes:
        - "**/*"

build-rs:
  extends: .base-rs
  stage: build
  script:
    - cargo build --verbose

build-rs-nightly:
  extends: .base-rs
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
  when: manual

lint-rs:
  extends: .base-rs
  stage: buildNonFunctional
  needs: [build-rs]
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --verbose

dependencies-outdated-rs:
  extends: .base-rs
  stage: buildNonFunctional
  needs: [build-rs]
  script:
      - cargo update --verbose
      - cargo build --verbose
  when: manual

dependencies-unused-rs:
  extends: .base-rs
  stage: buildNonFunctional
  needs: [build-rs]
  before_script:
    - cargo install cargo-udeps --locked
  script:
      - cargo +nightly udeps --all-targets
  when: manual

version-rs:
  extends: .base-rs
  stage: buildNonFunctional
  needs: [build-rs]
  script:
      - cargo update --verbose
      - cargo hack check --rust-version --workspace --all-targets --ignore-private
  when: manual

test-rs:
  extends: .base-rs
  stage: test
  needs: [build-rs]
  # image: docker:stable
  # services:
  #   - docker:dind
  script:
    - cargo test --verbose

    
# tarpaulin (Rust). Example: /^\d+.\d+% coverage/. jest --ci --coverage (NodeJS). Example: /All files[^|]*\|[^|]*\s+([\d\.]+)/.
# cargo-fuzz (libFuzzer support) https://gitlab.com/gitlab-org/security-products/demos/coverage-fuzzing/rust-fuzzing-example
# run unittests:
#   image: rust:latest
#   stage: test
#   before_script:
#     - cargo install --root . cargo2junit
#   script:
#     - cargo test -- -Z unstable-options --format json --report-time | bin/cargo2junit > report.xml
#   artifacts:
#     when: always
#     reports:
#       junit:
#         - report.xml
# coverage-rs:
  # stage: test
  # image: rust:latest
#   variables:
#     # Set an environment variable which causes LLVM to write coverage data to the specified location. This is arbitrary, but the path passed to grcov (the first argument) must contain these files or the coverage data won't be noticed.
#     LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
#   script:
#     # Run all your Rust-based tests
#     - cargo test --workspace
#     # Optionally, run some other command that exercises your code to get more coverage:
#     - ./bin/integration-tests --foo bar
#     # Create the output directory
#     - mkdir target/coverage
#     # This is a multi-line command. You can also write it all as one line if desired, just remove
#     # the '|' and all the newlines.
#     - |
#         grcov
#     # This path must match the setting in LLVM_PROFILE_FILE. If you're not getting the coverage
#     # you expect, look for '.profraw' files in other directories.
#         target/coverage
#     # If your target dir is modified, this will need to match...
#         --binary-path target/debug
#     # Where the source directory is expected
#         -s .
#     # Where to write the output; this should be a directory that exists.
#         -o target/coverage
#     # Exclude coverage of crates and Rust stdlib code. If you get unexpected coverage results from
#     # this (empty, for example), try different combinations of '--ignore-not-existing',
#     # '--ignore "$HOME/.cargo/**"' and see what kind of filtering gets you the coverage you're
#     # looking for.
#         --keep-only 'src/*'
#     # Doing both isn't strictly necessary, if you won't use the HTML version you can modify this
#     # line.
#         --output-types html,cobertura

#     # Extract just the top-level coverage number from the XML report.
#     - xmllint --xpath "concat('Coverage: ', 100 * string(//coverage/@line-rate), '%')" target/coverage/cobertura.xml
#   coverage: '/Coverage: \d+(?:\.\d+)?/'
#   artifacts:
#     paths:
#       - target/coverage/
#     reports:
#       coverage_report:
#         coverage_format: cobertura
#         path: target/coverage.xml

benchmark-rs:
  extends: .base-rs
  stage: testNonFunctional
  needs: [test-rs]
  script:
    - cargo bench --verbose
  when: manual
    
documentation-rs:
  extends: .base-rs
  stage: release
  needs: [test-rs]
  script:
    - cargo rustdoc --verbose
  when: manual
